### ISSUE TITLE
Need help? Available to help

### ISSUE THREAD

**Issue by petrussola** [fabrahaingo/find-shelter#1]
Hey! I am looking for open source projects to help Ukrainians and I found yours. Great idea! If you need help, just give me a shout 🙏 I am a React Frontend developer (the website is in Vue, I may not be able to help there) but I have done stuff with Express on the backend

**Comment by fabrahaingo** [comment]
Hey there !
I'm glad that you found this project. There are a lot of things you can do to help 👍
I'll add some feature suggestions on the repo in the next minutes. Meanwhile, do not hesitate tu suggest any improvements too 😊
